In [1]:
import numpy as np
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x[:10, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target)

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
standardScaler = StandardScaler()

In [8]:
standardScaler.fit(x_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [9]:
standardScaler.mean_

array([5.91875   , 3.06071429, 3.85982143, 1.24375   ])

In [12]:
standardScaler.scale_

array([0.83329501, 0.43329245, 1.77207807, 0.74746969])

In [15]:
x_train = standardScaler.transform(x_train)

In [16]:
x_train

array([[ 0.57752656,  0.3214589 ,  0.81270605,  1.41310078],
       [ 2.01759278, -0.14012311,  1.54630804,  1.1455314 ],
       [-0.98254518,  1.01383192, -1.38809992, -1.262593  ],
       [-0.14250655, -0.83249613,  0.02267314, -0.0585308 ],
       [ 1.65757622, -0.37091412,  1.37701528,  0.74417733],
       [ 0.57752656, -0.37091412,  0.24839683,  0.07525389],
       [-1.58257277,  0.3214589 , -1.38809992, -1.39637769],
       [ 1.17755415,  0.3214589 ,  1.03842974,  1.41310078],
       [ 0.69753207,  0.3214589 ,  0.69984421,  1.01174671],
       [-0.50252311, -1.06328713,  0.30482775, -0.0585308 ],
       [-1.22255622, -1.52486914, -0.3159124 , -0.32610018],
       [ 1.05754863,  0.3214589 ,  1.15129159,  1.41310078],
       [-1.34256174, -0.14012311, -1.38809992, -1.262593  ],
       [-1.58257277,  1.24462292, -1.61382361, -1.39637769],
       [ 2.13759829, -1.06328713,  1.71560081,  1.41310078],
       [-0.50252311, -1.29407814,  0.07910406,  0.07525389],
       [ 0.09750448, -1.

In [17]:
x_test_standard = standardScaler.transform(x_test)